dependencies:
  jfcarter2358: /home/jfcarter2358/personal/code/jc_add-ui-scaffolding/floorplan/examples/./.floorplan-packages/jfcarter2358
  local: .
dist_dir: /home/jfcarter2358/personal/code/jc_add-ui-scaffolding/floorplan/examples/dist
project_dir: /home/jfcarter2358/personal/code/jc_add-ui-scaffolding/floorplan/examples/.
static_dir: /home/jfcarter2358/personal/code/jc_add-ui-scaffolding/floorplan/examples/static
